[phases.setup]
# Install dependencies, then collect static
commands = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "python manage.py collectstatic --noinput"
]

[phases.start]
cmd = "gunicorn poketrade.wsgi:application --bind 0.0.0.0:$PORT"
